'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DXGrid_DisplayHeaderImage.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As DXGrid_DisplayHeaderImage.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DXGrid_DisplayHeaderImage.Properties.Settings())), DXGrid_DisplayHeaderImage.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return DXGrid_DisplayHeaderImage.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
